# config.py - CONFIGURACIÓN SIMPLIFICADA
import os

# Token del bot (obtener de @BotFather)
TOKEN = "8530361444:AAFZ-yZIFzDC0CVUvX-W14kTZGVKFITGBCE"

# Configuración simplificada
DOWNLOAD_PATH = "downloads"
MAX_FILE_SIZE = 50 * 1024 * 1024  # 50MB

# SIN SISTEMA DE PERMISOS - TODOS PUEDEN USARLO
# SIN ADMIN_ID - NO SE NECESITA